---
# tasks file for setup_proxy_nginx

- name: Установка Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Подмена веб-страницы
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.html
  when: "'vm_2' in inventory_hostname"
  notify: "Nginx Reloader

- name: Запуск Nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
