---
# tasks file for nginx_custom

- name: Установка Nginx 
  apt:
    name: "nginx"
    state: present

- name: Подмена веб-страницы
  ansible.builtin.template:
    src: proxy.conf
    dest: /etc/nginx/sites-enabled/default
  when: "'vm_2' in inventory_hostname" # Выполнится только тогда, когда в имени есть vm_2
  notify: "Nginx Reloader"

